openapi: 3.0.0
info:
  title: Campus Forum API
  version: 1.0.0
  description: API for interacting with the campus forum database.


paths:
  # User Management API Reference
  /users:
    $ref: 'user-management.yaml#/paths/~1users'
  /users/{user_id}:
    $ref: 'user-management.yaml#/paths/~1users~1{user_id}'
  /auth/login:
    $ref: 'user-management.yaml#/paths/~1auth~1login'
  /auth/refresh:
    $ref: 'user-management.yaml#/paths/~1auth~1refresh'

  # Post Management API Reference
  /posts:
    $ref: 'post-management.yaml#/paths/~1posts'
  /posts/{post_id}:
    $ref: 'post-management.yaml#/paths/~1posts~1{post_id}'
  /posts/hot:
    $ref: 'post-management.yaml#/paths/~1posts~1hot'
  /posts/search:
    $ref: 'post-management.yaml#/paths/~1posts~1search'
  
  # Comment Management API Reference
  /comments:
    $ref: 'comment-management.yaml#/paths/~1comments'
  /comments/{comment_id}:
    $ref: 'comment-management.yaml#/paths/~1comments~1{comment_id}'
  /posts/{post_id}/comments:
    $ref: 'comment-management.yaml#/paths/~1posts~1{post_id}~1comments'
  
  # Reaction System API Reference
  /emojis:
    $ref: 'reaction-system.yaml#/paths/~1emojis'
  /posts/{post_id}/reactions:
    $ref: 'reaction-system.yaml#/paths/~1posts~1{post_id}~1reactions'
  /comments/{comment_id}/reactions:
    $ref: 'reaction-system.yaml#/paths/~1comments~1{comment_id}~1reactions'
  
  # Calendar System API Reference
  /calendar/{user_id}/emojis:
    $ref: 'calendar-system.yaml#/paths/~1calendar~1{user_id}~1emojis'
  /calendar/{user_id}/pull-emoji:
    $ref: 'calendar-system.yaml#/paths/~1calendar~1{user_id}~1pull-emoji'
  
  # Tag Management API Reference
  /tags:
    $ref: 'tag-management.yaml#/paths/~1tags'
  /tags/{tag_id}:
    $ref: 'tag-management.yaml#/paths/~1tags~1{tag_id}'
  /posts/tags/{tag_id}:
    $ref: 'tag-management.yaml#/paths/~1posts~1tags~1{tag_id}'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
        username:
          type: string
        email:
          type: string
        email_verified:
          type: boolean
        phone_number:
          type: string
        phone_verified:
          type: boolean
        profile_picture_url:
          type: string
        role_id:
          type: integer
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewUser:
      type: object
      required:
        - username
        - password_hash
        - role_id
      properties:
        username:
          type: string
        password_hash:
          type: string
        email:
          type: string
        phone_number:
          type: string
        profile_picture_url:
          type: string
        role_id:
          type: integer

    Post:
      type: object
      properties:
        post_id:
          type: integer
        user_id:
          type: integer
        title:
          type: string
        content:
          type: string
        embedding:
          type: object
        comment_count:
          type: integer
        reaction_count:
          type: integer
        views_count:
          type: integer
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewPost:
      type: object
      required:
        - user_id
        - title
        - content
      properties:
        user_id:
          type: integer
        title:
          type: string
        content:
          type: string
        embedding:
          type: object

    Comment:
      type: object
      properties:
        comment_id:
          type: integer
        post_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        embedding:
          type: object
        parent_comment_id:
          type: integer
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewComment:
      type: object
      required:
        - post_id
        - user_id
        - content
      properties:
        post_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        embedding:
          type: object
        parent_comment_id:
          type: integer

    Emoji:
      type: object
      properties:
        emoji_id:
          type: integer
        emoji_code:
          type: string
        description:
          type: string
        image_url:
          type: string
        display_order:
          type: integer

    CalendarEmojiHistory:
      type: object
      properties:
        date:
          type: string
          format: date
        emoji:
          $ref: '#/components/schemas/Emoji'

    HotPost:
      type: object
      properties:
        postID:
          type: integer
        title:
          type: string
        content_preview:
          type: string
        comment_count:
          type: integer
        click_count:
          type: integer
        time:
          type: string
          format: date-time
        most_frequent_reaction_count:
          type: integer
        most_frequent_reaction:
          $ref: '#/components/schemas/Emoji'
        user_choice:
          type: string
          nullable: true
        background_url:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'

    Tag:
      type: object
      properties:
        tag_name:
          type: string
        isImportant:
          type: boolean
        tagcolor:
          type: string

    PostDetail:
      type: object
      properties:
        postID:
          type: integer
        title:
          type: string
        content:
          type: string
        reaction_list:
          type: array
          items:
            type: object
            properties:
              emoji:
                $ref: '#/components/schemas/Emoji'
              emoji_count:
                type: integer
        click_count:
          type: integer
        background_url:
          type: string
        time:
          type: string
          format: date-time
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        comments_list:
          type: array
          items:
            type: object
            properties:
              content:
                type: string
              parent_comment_id:
                type: integer
              time:
                type: string
                format: date-time
              reaction_list:
                type: array
                items:
                  type: object
                  properties:
                    emoji:
                      $ref: '#/components/schemas/Emoji'
                    emoji_count:
                      type: integer
              post_id:
                type: integer 