openapi: 3.0.0
info:
  title: Campus Forum API
  version: 1.0.0
  description: API for interacting with the campus forum database.

paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /posts:
    get:
      summary: Retrieve a list of posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /comments:
    get:
      summary: Retrieve a list of comments
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
        username:
          type: string
        email:
          type: string
        email_verified:
          type: boolean
        phone_number:
          type: string
        phone_verified:
          type: boolean
        profile_picture_url:
          type: string
        role_id:
          type: integer
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewUser:
      type: object
      required:
        - username
        - password_hash
        - role_id
      properties:
        username:
          type: string
        password_hash:
          type: string
        email:
          type: string
        phone_number:
          type: string
        profile_picture_url:
          type: string
        role_id:
          type: integer

    Post:
      type: object
      properties:
        post_id:
          type: integer
        user_id:
          type: integer
        title:
          type: string
        content:
          type: string
        embedding:
          type: object
        comment_count:
          type: integer
        reaction_count:
          type: integer
        views_count:
          type: integer
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewPost:
      type: object
      required:
        - user_id
        - title
        - content
      properties:
        user_id:
          type: integer
        title:
          type: string
        content:
          type: string
        embedding:
          type: object

    Comment:
      type: object
      properties:
        comment_id:
          type: integer
        post_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        embedding:
          type: object
        parent_comment_id:
          type: integer
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewComment:
      type: object
      required:
        - post_id
        - user_id
        - content
      properties:
        post_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        embedding:
          type: object
        parent_comment_id:
          type: integer 